"""add_common_area_affected

Revision ID: e627c77a261c
Revises: 0007_ai_priority_prediction
Create Date: 2026-07-16 00:26:23.097190
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = 'e627c77a261c'
down_revision: str | None = '0007_ai_priority_prediction'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_area_affected',
    sa.Column('complaint_id', sa.String(length=36), nullable=False, comment='FK to the complaint this student is affected by.'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='FK to the student who marked themselves as affected.'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_common_area_affected_complaint_id'), 'common_area_affected', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_common_area_affected_id'), 'common_area_affected', ['id'], unique=False)
    op.create_index('ix_common_area_affected_unique', 'common_area_affected', ['complaint_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_common_area_affected_user_id'), 'common_area_affected', ['user_id'], unique=False)
    op.alter_column('complaint_assignments', 'complaint_id',
               existing_type=sa.VARCHAR(length=36),
               comment='FK to the complaint this assignment belongs to (UNIQUE).',
               existing_nullable=False)
    op.alter_column('complaint_assignments', 'worker_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Name of the maintenance worker assigned to this complaint.',
               existing_nullable=False)
    op.alter_column('complaint_assignments', 'worker_type',
               existing_type=postgresql.ENUM('electrician', 'plumber', 'carpenter', 'civil', 'network', 'housekeeping', 'other', 'mason', 'cleaning_staff', name='maintenancetype'),
               comment='Type of maintenance worker (electrician, plumber, etc.).',
               existing_nullable=False)
    op.alter_column('complaint_assignments', 'scheduled_date',
               existing_type=sa.DATE(),
               comment='Date when the maintenance visit is scheduled.',
               existing_nullable=False)
    op.alter_column('complaint_assignments', 'scheduled_time',
               existing_type=sa.VARCHAR(length=50),
               comment="Optional time slot (e.g. '10:00–12:00').",
               existing_nullable=True)
    op.alter_column('complaint_assignments', 'admin_remarks',
               existing_type=sa.TEXT(),
               comment='Optional admin notes about the assignment.',
               existing_nullable=True)
    op.drop_constraint('complaint_assignments_complaint_id_key', 'complaint_assignments', type_='unique')
    op.drop_index('ix_complaint_assignments_complaint_id', table_name='complaint_assignments')
    op.create_index(op.f('ix_complaint_assignments_complaint_id'), 'complaint_assignments', ['complaint_id'], unique=True)
    op.create_index(op.f('ix_complaint_assignments_id'), 'complaint_assignments', ['id'], unique=False)
    op.alter_column('complaint_images', 'complaint_id',
               existing_type=sa.VARCHAR(length=36),
               comment='The complaint this image belongs to.',
               existing_comment='Parent complaint.',
               existing_nullable=False)
    op.alter_column('complaint_images', 'image_url',
               existing_type=sa.VARCHAR(length=1024),
               comment='Relative or absolute URL to the stored image file.',
               existing_comment='URL to the stored image file.',
               existing_nullable=False)
    op.alter_column('complaint_images', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='UUID primary key.',
               existing_nullable=False)
    op.alter_column('complaint_status_history', 'complaint_id',
               existing_type=sa.VARCHAR(length=36),
               comment='The complaint this history entry belongs to.',
               existing_comment='Parent complaint.',
               existing_nullable=False)
    op.alter_column('complaint_status_history', 'previous_status',
               existing_type=postgresql.ENUM('submitted', 'verified', 'scheduled', 'in_progress', 'completed', 'waiting_student_confirmation', 'closed', 'visit_failed_room_locked', 'reopened', name='complaintstatus'),
               comment='Status before the transition (NULL for the initial SUBMITTED entry).',
               existing_comment='Status before the transition (NULL for initial entry).',
               existing_nullable=True)
    op.alter_column('complaint_status_history', 'updated_by',
               existing_type=sa.VARCHAR(length=36),
               comment='User who triggered this status change.',
               existing_comment='User who triggered this transition.',
               existing_nullable=False)
    op.alter_column('complaint_status_history', 'remarks',
               existing_type=sa.TEXT(),
               comment='Optional free-text note explaining the transition.',
               existing_nullable=True)
    op.alter_column('complaint_status_history', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC time at which this transition occurred.',
               existing_comment='UTC time of the transition.',
               existing_nullable=False)
    op.alter_column('complaint_status_history', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='UUID primary key.',
               existing_nullable=False)
    op.drop_index('ix_csh_complaint_id', table_name='complaint_status_history')
    op.drop_index('ix_csh_id', table_name='complaint_status_history')
    op.drop_index('ix_csh_timestamp', table_name='complaint_status_history')
    op.drop_index('ix_csh_updated_by', table_name='complaint_status_history')
    op.create_index(op.f('ix_complaint_status_history_complaint_id'), 'complaint_status_history', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_complaint_status_history_id'), 'complaint_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_complaint_status_history_timestamp'), 'complaint_status_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_complaint_status_history_updated_by'), 'complaint_status_history', ['updated_by'], unique=False)
    op.alter_column('complaints', 'complaint_type',
               existing_type=postgresql.ENUM('personal', 'common_area', name='complainttype'),
               comment='Whether the complaint is for a personal room or a common area.',
               existing_comment='PERSONAL or COMMON_AREA.',
               existing_nullable=False)
    op.alter_column('complaints', 'category',
               existing_type=postgresql.ENUM('electrical', 'plumbing', 'carpentry', 'civil', 'internet', 'cleanliness', 'water', 'furniture', 'other', name='complaintcategory'),
               comment='Maintenance category (electrical, plumbing, …).',
               existing_comment='Maintenance category.',
               existing_nullable=False)
    op.alter_column('complaints', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'critical', name='complaintpriority'),
               comment='Urgency level of the complaint.',
               existing_comment='Urgency level.',
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::complaintpriority"))
    op.alter_column('complaints', 'status',
               existing_type=postgresql.ENUM('submitted', 'verified', 'scheduled', 'in_progress', 'completed', 'waiting_student_confirmation', 'closed', 'visit_failed_room_locked', 'reopened', name='complaintstatus'),
               comment='Current lifecycle state of the complaint.',
               existing_comment='Current lifecycle status.',
               existing_nullable=False,
               existing_server_default=sa.text("'submitted'::complaintstatus"))
    op.alter_column('complaints', 'maintenance_type',
               existing_type=postgresql.ENUM('electrician', 'plumber', 'carpenter', 'civil', 'network', 'housekeeping', 'other', 'mason', 'cleaning_staff', name='maintenancetype'),
               comment='Type of maintenance worker required (set by admin).',
               existing_comment='Type of maintenance worker assigned.',
               existing_nullable=True)
    op.alter_column('complaints', 'current_assignee',
               existing_type=sa.VARCHAR(length=255),
               comment='Name of the person / contractor currently handling the complaint.',
               existing_comment='Name of the current assignee or contractor.',
               existing_nullable=True)
    op.alter_column('complaints', 'room_number',
               existing_type=sa.VARCHAR(length=20),
               comment='Room number — required for PERSONAL complaints.',
               existing_comment='Room number for PERSONAL complaints.',
               existing_nullable=True)
    op.alter_column('complaints', 'block',
               existing_type=sa.VARCHAR(length=50),
               comment='Block / wing identifier for COMMON_AREA complaints.',
               existing_nullable=True)
    op.alter_column('complaints', 'floor',
               existing_type=sa.VARCHAR(length=10),
               comment='Floor identifier for COMMON_AREA complaints.',
               existing_nullable=True)
    op.alter_column('complaints', 'common_area',
               existing_type=sa.VARCHAR(length=100),
               comment="Name of the common area (e.g. 'Reading Room', 'Corridor').",
               existing_nullable=True)
    op.alter_column('complaints', 'qr_location_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Optional QR-code location tag scanned at the common area.',
               existing_nullable=True)
    op.alter_column('complaints', 'preferred_visit_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment="Student's preferred time slot for the maintenance visit.",
               existing_nullable=True)
    op.alter_column('complaints', 'hall_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Hall this complaint belongs to.',
               existing_comment='Parent hall.',
               existing_nullable=False)
    op.alter_column('complaints', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               comment='User (student) who raised the complaint.',
               existing_comment='Student who raised the complaint.',
               existing_nullable=False)
    op.alter_column('complaints', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='UUID primary key.',
               existing_nullable=False)
    op.alter_column('completion_slips', 'complaint_id',
               existing_type=sa.VARCHAR(length=36),
               comment='FK to the complaint this slip belongs to (UNIQUE).',
               existing_nullable=False)
    op.alter_column('completion_slips', 'hall_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Denormalized hall FK for fast schedule queries.',
               existing_nullable=False)
    op.alter_column('completion_slips', 'room_number',
               existing_type=sa.VARCHAR(length=20),
               comment='Snapshot of room number from the complaint.',
               existing_nullable=True)
    op.alter_column('completion_slips', 'worker_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Name of the worker who performed the repair.',
               existing_nullable=False)
    op.alter_column('completion_slips', 'worker_type',
               existing_type=postgresql.ENUM('electrician', 'plumber', 'carpenter', 'civil', 'network', 'housekeeping', 'other', 'mason', 'cleaning_staff', name='maintenancetype'),
               comment='Type of worker who performed the repair.',
               existing_nullable=False)
    op.alter_column('completion_slips', 'completion_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp when the repair was marked complete.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('completion_slips', 'work_done',
               existing_type=sa.TEXT(),
               comment='Description of the work performed (admin-supplied).',
               existing_nullable=False)
    op.alter_column('completion_slips', 'admin_remarks',
               existing_type=sa.TEXT(),
               comment='Optional additional remarks from the admin.',
               existing_nullable=True)
    op.alter_column('completion_slips', 'student_comment',
               existing_type=sa.TEXT(),
               comment="Student's comment on the repair outcome.",
               existing_nullable=True)
    op.alter_column('completion_slips', 'student_confirmation_status',
               existing_type=sa.VARCHAR(length=20),
               comment='Student confirmation state: pending | confirmed | rejected.',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('completion_slips', 'student_confirmation_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp when the student confirmed or rejected.',
               existing_nullable=True)
    op.drop_constraint('completion_slips_complaint_id_key', 'completion_slips', type_='unique')
    op.drop_index('ix_completion_slips_complaint_id', table_name='completion_slips')
    op.create_index(op.f('ix_completion_slips_complaint_id'), 'completion_slips', ['complaint_id'], unique=True)
    op.create_index(op.f('ix_completion_slips_id'), 'completion_slips', ['id'], unique=False)
    op.alter_column('halls', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='UUID primary key.',
               existing_nullable=False)
    op.drop_constraint('halls_code_key', 'halls', type_='unique')
    op.drop_constraint('halls_name_key', 'halls', type_='unique')
    op.alter_column('notifications', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment='UUID primary key.',
               existing_nullable=False)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment='FK to the user who should see this notification.',
               existing_nullable=False)
    op.alter_column('notifications', 'complaint_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Optional FK to the related complaint.',
               existing_nullable=True)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               comment='The notification message text.',
               existing_nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               comment='Whether the user has read this notification.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp when notification was created.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'hall_verification_status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='hallverificationstatus'),
               comment="Whether this student's hall affiliation has been verified by the admin.",
               existing_comment="Whether this student's hall affiliation has been verified.",
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::hallverificationstatus"))
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='UUID primary key.',
               existing_nullable=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment='UUID primary key.',
               existing_nullable=False)
    op.alter_column('users', 'hall_verification_status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='hallverificationstatus'),
               comment="Whether this student's hall affiliation has been verified.",
               existing_comment="Whether this student's hall affiliation has been verified by the admin.",
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::hallverificationstatus"))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp when notification was created.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether the user has read this notification.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='The notification message text.',
               existing_nullable=False)
    op.alter_column('notifications', 'complaint_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Optional FK to the related complaint.',
               existing_nullable=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='FK to the user who should see this notification.',
               existing_nullable=False)
    op.alter_column('notifications', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='UUID primary key.',
               existing_nullable=False)
    op.create_unique_constraint('halls_name_key', 'halls', ['name'])
    op.create_unique_constraint('halls_code_key', 'halls', ['code'])
    op.alter_column('halls', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment='UUID primary key.',
               existing_nullable=False)
    op.drop_index(op.f('ix_completion_slips_id'), table_name='completion_slips')
    op.drop_index(op.f('ix_completion_slips_complaint_id'), table_name='completion_slips')
    op.create_index('ix_completion_slips_complaint_id', 'completion_slips', ['complaint_id'], unique=False)
    op.create_unique_constraint('completion_slips_complaint_id_key', 'completion_slips', ['complaint_id'])
    op.alter_column('completion_slips', 'student_confirmation_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp when the student confirmed or rejected.',
               existing_nullable=True)
    op.alter_column('completion_slips', 'student_confirmation_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Student confirmation state: pending | confirmed | rejected.',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('completion_slips', 'student_comment',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Student's comment on the repair outcome.",
               existing_nullable=True)
    op.alter_column('completion_slips', 'admin_remarks',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Optional additional remarks from the admin.',
               existing_nullable=True)
    op.alter_column('completion_slips', 'work_done',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Description of the work performed (admin-supplied).',
               existing_nullable=False)
    op.alter_column('completion_slips', 'completion_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp when the repair was marked complete.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('completion_slips', 'worker_type',
               existing_type=postgresql.ENUM('electrician', 'plumber', 'carpenter', 'civil', 'network', 'housekeeping', 'other', 'mason', 'cleaning_staff', name='maintenancetype'),
               comment=None,
               existing_comment='Type of worker who performed the repair.',
               existing_nullable=False)
    op.alter_column('completion_slips', 'worker_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Name of the worker who performed the repair.',
               existing_nullable=False)
    op.alter_column('completion_slips', 'room_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Snapshot of room number from the complaint.',
               existing_nullable=True)
    op.alter_column('completion_slips', 'hall_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Denormalized hall FK for fast schedule queries.',
               existing_nullable=False)
    op.alter_column('completion_slips', 'complaint_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='FK to the complaint this slip belongs to (UNIQUE).',
               existing_nullable=False)
    op.alter_column('complaints', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment='UUID primary key.',
               existing_nullable=False)
    op.alter_column('complaints', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               comment='Student who raised the complaint.',
               existing_comment='User (student) who raised the complaint.',
               existing_nullable=False)
    op.alter_column('complaints', 'hall_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Parent hall.',
               existing_comment='Hall this complaint belongs to.',
               existing_nullable=False)
    op.alter_column('complaints', 'preferred_visit_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment="Student's preferred time slot for the maintenance visit.",
               existing_nullable=True)
    op.alter_column('complaints', 'qr_location_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Optional QR-code location tag scanned at the common area.',
               existing_nullable=True)
    op.alter_column('complaints', 'common_area',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Name of the common area (e.g. 'Reading Room', 'Corridor').",
               existing_nullable=True)
    op.alter_column('complaints', 'floor',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Floor identifier for COMMON_AREA complaints.',
               existing_nullable=True)
    op.alter_column('complaints', 'block',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Block / wing identifier for COMMON_AREA complaints.',
               existing_nullable=True)
    op.alter_column('complaints', 'room_number',
               existing_type=sa.VARCHAR(length=20),
               comment='Room number for PERSONAL complaints.',
               existing_comment='Room number — required for PERSONAL complaints.',
               existing_nullable=True)
    op.alter_column('complaints', 'current_assignee',
               existing_type=sa.VARCHAR(length=255),
               comment='Name of the current assignee or contractor.',
               existing_comment='Name of the person / contractor currently handling the complaint.',
               existing_nullable=True)
    op.alter_column('complaints', 'maintenance_type',
               existing_type=postgresql.ENUM('electrician', 'plumber', 'carpenter', 'civil', 'network', 'housekeeping', 'other', 'mason', 'cleaning_staff', name='maintenancetype'),
               comment='Type of maintenance worker assigned.',
               existing_comment='Type of maintenance worker required (set by admin).',
               existing_nullable=True)
    op.alter_column('complaints', 'status',
               existing_type=postgresql.ENUM('submitted', 'verified', 'scheduled', 'in_progress', 'completed', 'waiting_student_confirmation', 'closed', 'visit_failed_room_locked', 'reopened', name='complaintstatus'),
               comment='Current lifecycle status.',
               existing_comment='Current lifecycle state of the complaint.',
               existing_nullable=False,
               existing_server_default=sa.text("'submitted'::complaintstatus"))
    op.alter_column('complaints', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'critical', name='complaintpriority'),
               comment='Urgency level.',
               existing_comment='Urgency level of the complaint.',
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::complaintpriority"))
    op.alter_column('complaints', 'category',
               existing_type=postgresql.ENUM('electrical', 'plumbing', 'carpentry', 'civil', 'internet', 'cleanliness', 'water', 'furniture', 'other', name='complaintcategory'),
               comment='Maintenance category.',
               existing_comment='Maintenance category (electrical, plumbing, …).',
               existing_nullable=False)
    op.alter_column('complaints', 'complaint_type',
               existing_type=postgresql.ENUM('personal', 'common_area', name='complainttype'),
               comment='PERSONAL or COMMON_AREA.',
               existing_comment='Whether the complaint is for a personal room or a common area.',
               existing_nullable=False)
    op.drop_index(op.f('ix_complaint_status_history_updated_by'), table_name='complaint_status_history')
    op.drop_index(op.f('ix_complaint_status_history_timestamp'), table_name='complaint_status_history')
    op.drop_index(op.f('ix_complaint_status_history_id'), table_name='complaint_status_history')
    op.drop_index(op.f('ix_complaint_status_history_complaint_id'), table_name='complaint_status_history')
    op.create_index('ix_csh_updated_by', 'complaint_status_history', ['updated_by'], unique=False)
    op.create_index('ix_csh_timestamp', 'complaint_status_history', ['timestamp'], unique=False)
    op.create_index('ix_csh_id', 'complaint_status_history', ['id'], unique=False)
    op.create_index('ix_csh_complaint_id', 'complaint_status_history', ['complaint_id'], unique=False)
    op.alter_column('complaint_status_history', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment='UUID primary key.',
               existing_nullable=False)
    op.alter_column('complaint_status_history', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC time of the transition.',
               existing_comment='UTC time at which this transition occurred.',
               existing_nullable=False)
    op.alter_column('complaint_status_history', 'remarks',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Optional free-text note explaining the transition.',
               existing_nullable=True)
    op.alter_column('complaint_status_history', 'updated_by',
               existing_type=sa.VARCHAR(length=36),
               comment='User who triggered this transition.',
               existing_comment='User who triggered this status change.',
               existing_nullable=False)
    op.alter_column('complaint_status_history', 'previous_status',
               existing_type=postgresql.ENUM('submitted', 'verified', 'scheduled', 'in_progress', 'completed', 'waiting_student_confirmation', 'closed', 'visit_failed_room_locked', 'reopened', name='complaintstatus'),
               comment='Status before the transition (NULL for initial entry).',
               existing_comment='Status before the transition (NULL for the initial SUBMITTED entry).',
               existing_nullable=True)
    op.alter_column('complaint_status_history', 'complaint_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Parent complaint.',
               existing_comment='The complaint this history entry belongs to.',
               existing_nullable=False)
    op.alter_column('complaint_images', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment='UUID primary key.',
               existing_nullable=False)
    op.alter_column('complaint_images', 'image_url',
               existing_type=sa.VARCHAR(length=1024),
               comment='URL to the stored image file.',
               existing_comment='Relative or absolute URL to the stored image file.',
               existing_nullable=False)
    op.alter_column('complaint_images', 'complaint_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Parent complaint.',
               existing_comment='The complaint this image belongs to.',
               existing_nullable=False)
    op.drop_index(op.f('ix_complaint_assignments_id'), table_name='complaint_assignments')
    op.drop_index(op.f('ix_complaint_assignments_complaint_id'), table_name='complaint_assignments')
    op.create_index('ix_complaint_assignments_complaint_id', 'complaint_assignments', ['complaint_id'], unique=False)
    op.create_unique_constraint('complaint_assignments_complaint_id_key', 'complaint_assignments', ['complaint_id'])
    op.alter_column('complaint_assignments', 'admin_remarks',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Optional admin notes about the assignment.',
               existing_nullable=True)
    op.alter_column('complaint_assignments', 'scheduled_time',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Optional time slot (e.g. '10:00–12:00').",
               existing_nullable=True)
    op.alter_column('complaint_assignments', 'scheduled_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date when the maintenance visit is scheduled.',
               existing_nullable=False)
    op.alter_column('complaint_assignments', 'worker_type',
               existing_type=postgresql.ENUM('electrician', 'plumber', 'carpenter', 'civil', 'network', 'housekeeping', 'other', 'mason', 'cleaning_staff', name='maintenancetype'),
               comment=None,
               existing_comment='Type of maintenance worker (electrician, plumber, etc.).',
               existing_nullable=False)
    op.alter_column('complaint_assignments', 'worker_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Name of the maintenance worker assigned to this complaint.',
               existing_nullable=False)
    op.alter_column('complaint_assignments', 'complaint_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='FK to the complaint this assignment belongs to (UNIQUE).',
               existing_nullable=False)
    op.drop_index(op.f('ix_common_area_affected_user_id'), table_name='common_area_affected')
    op.drop_index('ix_common_area_affected_unique', table_name='common_area_affected')
    op.drop_index(op.f('ix_common_area_affected_id'), table_name='common_area_affected')
    op.drop_index(op.f('ix_common_area_affected_complaint_id'), table_name='common_area_affected')
    op.drop_table('common_area_affected')
    # ### end Alembic commands ###
