"""add_workers_and_complaint_relationships

Revision ID: faeff36ba00e
Revises: e627c77a261c
Create Date: 2026-07-16 13:40:32.789589
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'faeff36ba00e'
down_revision: str | None = 'e627c77a261c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Full name of the worker.'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='Phone number of the worker.'),
    sa.Column('specialization', sa.Enum('electrician', 'plumber', 'carpenter', 'cleaning_staff', 'network_staff', 'civil_maintenance', name='workerspecialization', create_constraint=True), nullable=False, comment='Specialization of the worker.'),
    sa.Column('availability_status', sa.Enum('available', 'busy', 'on_leave', name='workeravailability', create_constraint=True), nullable=False, comment='Availability status of the worker.'),
    sa.Column('skill_rating', sa.Float(), nullable=False, comment='Skill rating out of 5.0.'),
    sa.Column('experience_years', sa.Integer(), nullable=False, comment='Years of work experience.'),
    sa.Column('experience_level', sa.Enum('junior', 'intermediate', 'senior', name='workerexperiencelevel', create_constraint=True), nullable=False, comment='Worker experience level.'),
    sa.Column('completed_jobs', sa.Integer(), nullable=False, comment='Count of completed jobs by this worker.'),
    sa.Column('hall_id', sa.String(length=36), nullable=False, comment='Hall this worker belongs to.'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_availability_status'), 'workers', ['availability_status'], unique=False)
    op.create_index(op.f('ix_workers_hall_id'), 'workers', ['hall_id'], unique=False)
    op.create_index(op.f('ix_workers_id'), 'workers', ['id'], unique=False)
    op.create_index(op.f('ix_workers_specialization'), 'workers', ['specialization'], unique=False)
    op.add_column('complaints', sa.Column('assigned_worker_id', sa.String(length=36), nullable=True, comment='Worker assigned to resolve this complaint.'))
    op.add_column('complaints', sa.Column('recommended_worker_id', sa.String(length=36), nullable=True, comment='Worker recommended by the AI for this complaint.'))
    op.add_column('complaints', sa.Column('recommendation_score', sa.Float(), nullable=True, comment='AI recommendation match score percentage (0-100).'))
    op.add_column('complaints', sa.Column('recommendation_reason', sa.Text(), nullable=True, comment='AI recommendation reasoning explaining the choice.'))
    op.create_index(op.f('ix_complaints_assigned_worker_id'), 'complaints', ['assigned_worker_id'], unique=False)
    op.create_index(op.f('ix_complaints_recommended_worker_id'), 'complaints', ['recommended_worker_id'], unique=False)
    op.create_foreign_key(None, 'complaints', 'workers', ['assigned_worker_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'complaints', 'workers', ['recommended_worker_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_index(op.f('ix_complaints_recommended_worker_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_assigned_worker_id'), table_name='complaints')
    op.drop_column('complaints', 'recommendation_reason')
    op.drop_column('complaints', 'recommendation_score')
    op.drop_column('complaints', 'recommended_worker_id')
    op.drop_column('complaints', 'assigned_worker_id')
    op.drop_index(op.f('ix_workers_specialization'), table_name='workers')
    op.drop_index(op.f('ix_workers_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_hall_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_availability_status'), table_name='workers')
    op.drop_table('workers')
    # ### end Alembic commands ###
